name: Temporary Secret Check

on:
  workflow_dispatch:  # Allows manual trigger via GitHub Actions UI

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check FG_AZURE_CLIENT_ID
        run: |
          if [ -z "${{ secrets.FG_AZURE_CLIENT_ID }}" ]; then
            echo "FG_AZURE_CLIENT_ID is not set!"
            exit 1
          else
            echo "FG_AZURE_CLIENT_ID is set."
          fi

      - name: Check FG_AZURE_TENANT_ID
        run: |
          if [ -z "${{ secrets.FG_AZURE_TENANT_ID }}" ]; then
            echo "FG_AZURE_TENANT_ID is not set!"
            exit 1
          else
            echo "FG_AZURE_TENANT_ID is set."
          fi

      - name: Check FG_AZURE_SUBSCRIPTION_ID
        run: |
          if [ -z "${{ secrets.FG_AZURE_SUBSCRIPTION_ID }}" ]; then
            echo "FG_AZURE_SUBSCRIPTION_ID is not set!"
            exit 1
          else
            echo "FG_AZURE_SUBSCRIPTION_ID is set."
          fi
