name: Debug Azure Login

on:
  workflow_dispatch:  # Allows manual trigger via GitHub Actions UI

jobs:
  debug-azure-login:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write 
      contents: read 

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "FG_AZURE_CLIENT_ID: ${{ secrets.FG_AZURE_CLIENT_ID }}"
          echo "FG_AZURE_TENANT_ID: ${{ secrets.FG_AZURE_TENANT_ID }}"
          echo "FG_AZURE_SUBSCRIPTION_ID: ${{ secrets.FG_AZURE_SUBSCRIPTION_ID }}"

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FG_AZURE_SUBSCRIPTION_ID }}
          enable-federated-credentials: true
          auth-type: 'sp'
