name: Trigger auto deployment for fgweb

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fgweb-AutoDeployTrigger-97be87a2-b195-4f78-859f-20d9320b1371.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FGWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FGWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FGWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.FGWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FGWEB_REGISTRY_PASSWORD }}
          containerAppName: fgweb
          resourceGroup: finexus
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


